name: CodeQL

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-debian:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linters
        run: npm install -g htmlhint stylelint stylelint-config-standard eslint
      - name: HTML
        run: htmlhint "**/*.html" --ignore "assets/**"
      - name: CSS
        run: |
          stylelint "**/*.css" \
          --config /usr/local/lib/node_modules/stylelint-config-standard/index.js \
          --allow-empty-input \
          --fix \
          --rule 'no-duplicate-selectors: null' \
          --rule 'no-descending-specificity: null' \
          --rule 'declaration-block-no-shorthand-property-overrides: null' \
          --rule 'font-family-no-duplicate-names: null'
      - name: JS
        run: 'npx eslint . --no-eslintrc --rule "semi: [2, always]" --rule "no-console: 0" --env browser'